name: Build

on:
  push:
    branches:
      - main
      - next
      - next-major
      - '[0-9]+.[0-9]+.x'
      - alpha
      - beta
      - feature/*
      - fix/*
  pull_request:
    branches:
      - main
      - next
      - next-major
      - '[0-9]+.[0-9]+.x'
      - alpha
      - beta
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
